# Generated by Django 6.0.4 on 2026-04-28 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewsession',
            name='topics',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
