# Generated by Django 6.0.4 on 2026-04-28 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_interviewsession_topics'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='user_answer',
        ),
        migrations.AddField(
            model_name='answer',
            name='answer_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='answer',
            name='code',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='answer',
            name='output',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='constraints',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='input_example',
            field=models.TextField(blank=True, null=True),
        ),
    ]
