# Generated by Django 6.0.5 on 2026-06-08 04:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_job_deadline_job_posted_at_job_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewsession',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.category'),
        ),
    ]
