# Generated by Django 6.0.5 on 2026-06-08 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_interviewsession_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewflow',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.category'),
        ),
    ]
