# Generated by Django 6.0.4 on 2026-06-16 12:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_interviewflow_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='score',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
